-- SCHEMA: MadDadSkills

DROP SCHEMA IF EXISTS MadDadSkills CASCADE;
CREATE SCHEMA MadDadSkills
    AUTHORIZATION laura;
SET SCHEMA 'MadDadSkills';

DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS LEARNING_MODULE CASCADE;
DROP TABLE IF EXISTS LESSON CASCADE;
DROP TABLE IF EXISTS TASK_STATUS CASCADE;
DROP TABLE IF EXISTS TASKS CASCADE;

CREATE TABLE USERS (
    userID INTEGER GENERATED ALWAYS AS IDENTITY,
    firstName VARCHAR(30) NOT NULL,
    lastName VARCHAR(30) NOT NULL,
    dateOfBirth DATE NOT NULL,
    CONSTRAINT USERS_PK PRIMARY KEY (userID)
);

CREATE TABLE LEARNING_MODULE (
	moduleID INTEGER NOT NULL,
	moduleType VARCHAR(50),
	moduleName VARCHAR(50),
	description VARCHAR(255),
	CONSTRAINT LEARNING_MODULE_PK PRIMARY KEY (moduleID)
);

CREATE TABLE LESSON (
	lessonID INTEGER NOT NULL,
	name VARCHAR(50) NOT NULL,
	sequence INTEGER NOT NULL,
	lesson VARCHAR(300),
	description VARCHAR(255),
	parentModuleID INTEGER NOT NULL,
	CONSTRAINT LESSON_PK PRIMARY KEY (lessonID),
	CONSTRAINT LESSON_FK FOREIGN KEY (parentModuleID) REFERENCES LEARNING_MODULE (moduleID)
		ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE DOMAIN TASK_STATUS_DOMAIN AS VARCHAR(12) 
    CONSTRAINT TASK_STATUS_VALUE CHECK (
        VALUE IN ('Completed', 'In progress', 'Not Started')
	);

CREATE TABLE TASK_STATUS (
	taskStatusID INTEGER GENERATED ALWAYS AS IDENTITY,
	status TASK_STATUS_DOMAIN NOT NULL,
	CONSTRAINT TASK_STATUS_PK PRIMARY KEY (taskStatusID)
);

CREATE TABLE TASKS (
    taskID INTEGER GENERATED ALWAYS AS IDENTITY,
    userID INTEGER NOT NULL,
    lessonID,
    taskStatusID,
    CONSTRAINT TASKS_FK_USER FOREIGN KEY (userID) REFERENCES USERS (userID) 
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT TASKS_FK_MINIMOD FOREIGN KEY (lessonID) REFERENCES LESSON (lessonID) 
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT TASKS_FK_task FOREIGN KEY (taskStatusID) REFERENCES TASK_STATUS (taskStatusID) 
        ON UPDATE CASCADE ON DELETE CASCADE
);